/**
 * B6: EN-only. Every user-facing string lives here — components never
 * hard-code text. Flat object, keyed by screen.
 */
export const strings = {
  app: {
    name: "AutoAudit",
    pilotBadge: "Pilot preview",
    tagline: "Live BIM compliance audits",
  },
  nav: {
    overview: "Overview",
    setup: "Setup",
    run: "Run",
    results: "Results",
    approvals: "Approvals",
    rules: "Rules",
    ruleBuilder: "Rule Builder",
    history: "History",
  },
  results: {
    title: "Results",
    description: "The most recent audit run.",
    emptyTitle: "No runs yet",
    emptyBody: "Run an audit and its results will show up here.",
    emptyAction: "Run an audit",
  },
  health: {
    revit: "Revit",
    forma: "Forma",
    lod: "LOD",
    spatial: "Spatial",
    up: "Connected",
    unconfigured: "Not configured — see PILOT_INSTALL.md",
    error: "Error",
    checking: "Checking…",
  },
  topbar: {
    run: "Run",
    theme: "Toggle theme",
  },
  comingInM2: {
    title: "Coming in M2",
    body: "Use the Streamlit console at :8501 for this workflow until M2 ships.",
    link: "Open Streamlit console",
  },
  rules: {
    title: "Rules library",
    description: "Rule files in config/ — one YAML per scenario.",
    newRule: "New rule",
    extractFromPdf: "Extract from PDF",
    columnFile: "File",
    columnScenario: "Scenario",
    columnRuleCount: "Rules",
    columnCategories: "Categories",
    columnUpdated: "Updated",
    edit: "Edit",
    deleteFile: "Delete file",
    exportIds: "Export IDS",
    emptyTitle: "No rule files yet",
    emptyBody: "Create your first rule to see it listed here.",
    emptyAction: "New rule",
    errorTooltip: "This file failed to load — see server logs",
    confirmDeleteTitle: "Delete rule file",
    confirmDeleteBody: (name: string) => `Delete ${name}? This cannot be undone.`,
    ruleCount: (n: number) => `${n} rule${n === 1 ? "" : "s"}`,
    geometryCount: (n: number) => `${n} geometry rule${n === 1 ? "" : "s"}`,
    columnRuleId: "ID",
    columnCategory: "Category",
    columnParameter: "Parameter",
    columnRequirement: "Requirement",
    columnSeverity: "Severity",
    columnActionKind: "Action",
    actionIssue: "ACC issue",
    actionFix: "Auto-fix",
  },
  builder: {
    title: "New rule",
    titleEdit: "Edit rule",
    ruleTab: "Parameter rule",
    geometryTab: "Geometry rule",
    loadExisting: "Load existing",
    draftTitle: "Draft from text",
    draftPlaceholder:
      "All doors on fire-rated walls must have a matching Fire Rating…",
    generate: "Generate",
    generating: "Generating…",
    generateMissingKey: "Set ANTHROPIC_API_KEY in Setup to enable AI drafting.",
    importIds: "Import IDS",
    scopeTitle: "1 · Scope",
    category: "Category",
    parameter: "Parameter",
    parameterOther: "Other (shared parameter)…",
    parameterOtherLabel: "Parameter name",
    boundParameterCaption: "Not in the catalog — read-only/binding can't be checked.",
    readOnly: "read-only",
    readOnlyTooltip: "Read-only — cannot be an auto-fix write target",
    scopeFilterToggle: "Scope filter (optional)",
    scopeFilterHint:
      "Only applies to elements where another parameter matches a pattern. Leave blank to apply to every element.",
    scopeFilterParam: "Parameter",
    scopeFilterPattern: "Pattern",
    checkTitle: "2 · Check",
    requirement: "Requirement",
    requirementLegacyBanner:
      "Legacy requirement — preserved, not editable here. Edit the YAML directly or leave this rule as-is.",
    requirementOptions: {
      present_and_nonempty: "Has a value (not empty)",
      canonical_format: "Canonical format (auto-fix — no pattern needed)",
      numeric_compare: "Numeric comparison (operator + threshold)",
      matches_regex: "Match pattern (regex)",
      unique_in_set: "Unique across the project",
      relation_compare: "Compare against a related element",
    },
    canonicalCaption: "canonical_format's fix is inherent — normalize always applies.",
    patternLabel: "Pattern (regex)",
    patternNegate: "Negate — must NOT match",
    patternSkipIfEmpty: "Only check when a value is present",
    patternTest: "Test value",
    patternTestMatches: "Matches",
    patternTestNoMatch: "Does not match",
    uniqueCaption:
      "unique_in_set is always Path-B auto — a duplicate value is renumbered to the next available value.",
    operator: "Operator",
    threshold: "Threshold",
    unit: "Unit",
    thresholdZeroWarning:
      "A threshold of 0 with this operator always passes for every non-negative value — set a real threshold.",
    relationMode: "Compare against",
    relationModeDirect: "Direct — a related element's parameter",
    relationModeLookup: "Lookup table (code table)",
    otherParam: "Related parameter",
    otherParamHint: "e.g. host.Fire Rating",
    compareKind: "Compare kind",
    compareKindOptions: {
      numeric: "Number",
      fire_rating: "Fire rating (HR/MIN → minutes)",
      string: "String (== / !=)",
    },
    lookupTable: "Lookup table",
    lookupNew: "Create new table…",
    lookupMissing: "Create the table below, then pick it here.",
    severityTitle: "3 · Severity",
    severityOptions: {
      severity_low: "Low",
      severity_medium: "Medium",
      severity_high: "High",
    },
    actionTitle: "4 · Action",
    actionSelect: "Handle violations by",
    actionOptions: {
      issue: "Create ACC issue",
      normalize: "Auto-fix — normalize value",
      compose_template: "Auto-fix — compose from other parameters",
      inherit_from_host: "Auto-fix — inherit from host",
      set_fixed: "Auto-fix — set fixed value",
    },
    actionHint:
      "Auto-fix proposes via an approve-gated ACC issue → approve → write Revit. Create ACC issue only opens an issue for a human.",
    writeTarget: "Write target",
    writeTargetOptions: {
      auto: "Auto-detect",
      instance: "Parameter (instance)",
      type: "Parameter (type)",
      family: "Rename family",
      rename_type: "Rename type",
    },
    writeTargetAutoCaption:
      "The engine resolves the write target per element at run time (Family Name → rename family, Type Name → rename type, a type-carried parameter → type, else instance).",
    writeTargetReadOnly:
      "This parameter is read-only — it cannot be an auto-fix write target. Pick another parameter or switch to Create ACC issue.",
    normalizeKind: "Normalize kind",
    normalizeKindOptions: {
      auto: "Auto — the engine tries every form and picks the one matching Pattern",
      duration: "Duration (min/hr)",
      length: "Length (mm/cm/m)",
      area: "Area (m²/sf)",
      fire_rating: "Fire rating (= duration)",
      family_name: "Name: collapse separators → _",
      template: "Name: regex → template",
      map: "Fixed mapping table (text)",
      reference: "Reference set (approved values)",
    },
    normalizeAutoCaption:
      "Auto needs a Pattern (above) to pick the matching output — no format/unit to declare.",
    normalizeFormat: "Output format",
    normalizeSource: "Source regex",
    normalizeSourceHint: "Use named groups (?P<token>...) to capture tokens.",
    normalizeTargetTemplate: "Target template",
    normalizeMapTitle: "Mapping table",
    normalizeMapHint: "variant = canonical, one per line",
    normalizeReference: "Reference set",
    referenceNew: "Create new set…",
    referenceMissing: "Define the set below, then pick it here.",
    inheritWhenEmpty: "Inherit from host when empty, then normalize",
    hostParam: "Host parameter to inherit (blank = same name)",
    composeTemplate: "Template",
    composeTemplateHint: "{_containing_space}-{Reference Level}-{System Name}-{seq}",
    fixedValue: "Fixed value",
    previewTitle: "Preview",
    previewSample: "Sample value",
    previewNone: "Not parseable → None → routes to a Path A ACC issue",
    previewError: "Preview error",
    saveTitle: "5 · Save",
    scenario: "Scenario",
    scenarioNewPlaceholder: "e.g. vp_bep",
    scenarioHint: (name: string) => `Will save to config/rules.${name || "…"}.yaml`,
    save: "Save rule",
    saving: "Saving…",
    savedTitle: "Rule saved",
    savedBody: (path: string) => `Saved to ${path}`,
    openRules: "Open Rules",
    overwriteTitle: "Overwrite existing file",
    overwriteBody:
      "A rules file with this scenario name already exists. Overwrite it with this rule?",
    exportIds: "Export IDS",
    validationFooterTitle: "Fix before saving",
    validationFooterOk: "No blocking issues",
    idLabel: "Rule ID",
    idHint: "lowercase, dot-separated: category.parameter.check",
    descriptionLabel: "Description (used in reports)",
  },
  geometry: {
    idLabel: "Rule ID",
    idHint: "lowercase, dot-separated: category.context.check",
    descriptionLabel: "Description",
    checkTypeLabel: "Check type",
    checkTypeOptions: {
      clearance_min: "Minimum clearance",
      clearance_max: "Maximum clearance",
      spatial_containment: "Must be inside a named space",
      min_spacing: "Minimum spacing between siblings",
    },
    thresholdMm: "Threshold (mm)",
    direction: "Direction",
    directionOptions: {
      below: "Below",
      above: "Above",
      horizontal: "Horizontal",
    },
    categoryLabel: "Category to check",
    referenceTitle: "Reference element",
    referenceCategory: "Reference category",
    referenceSource: "Source",
    referenceSourceOptions: {
      same_model: "Same model",
      linked_arch: "Linked — Architectural",
      linked_struct: "Linked — Structural",
      linked_mep: "Linked — MEP",
    },
    referenceLinkHint: "Specific link file (optional)",
    referenceLinkHintPlaceholder: "HVAC",
    spatialFilterToggle: "Spatial filter — restrict scope (optional)",
    spatialFilterCategory: "Container category",
    spatialFilterNameContains: "Container name contains",
  },
  dashboard: {
    title: "Overview",
    description: "The latest audit run at a glance, plus your compliance trend.",
    project: "Project",
    model: "Model",
    mode: "Mode",
    profile: "Profile",
    liveModel: "Open in Revit",
    liveModelNone: "No Revit model open",
    runOnThis: "Run audit on this model",
    lastRun: "Last run",
    openResults: "Open results",
    verificationReport: "Verification report",
    approvalsPendingBanner: (n: number) =>
      `${n} proposal${n === 1 ? "" : "s"} pending approval`,
    review: "Review",
    complianceTrend: "Compliance trend",
    runsHistory: "Runs history",
    emptyTitle: "Run your first audit",
    emptyBody:
      "No audits have run yet. Kick off the au_demo profile to see AutoAudit in action.",
    emptyAction: "Run your first audit",
  },
  setup: {
    title: "Setup",
    description:
      "Review and edit connections, run diagnostics, and see the profiles and rule files used by this pilot deployment.",
    statusTitle: "Status",
    profilesTitle: "Profiles",
    columnName: "Name",
    columnRules: "Rules",
    columnMode: "Mode",
    columnStatus: "Status",
    statusOk: "OK",
    rulesFilesTitle: "Rules files",
    emptyProfiles: "No profiles found.",

    connectionsTitle: "Connections",
    connectionsNote:
      "Change the ACC/Forma project or keys here when you switch models. Values are stored in .env on this machine — never shown in full once set. Restart the service for saved changes to take effect.",
    envGroupForma: "Forma / ACC",
    envGroupAnthropic: "Anthropic",
    envGroupOther: "Other",
    envColumnKey: "Key",
    envColumnStatus: "Status",
    envColumnValue: "Value",
    envSet: "Set",
    envNotSet: "Not set",
    envEdit: "Edit",
    envReveal: "Reveal",
    envHide: "Hide",
    envSave: "Save",
    envSaving: "Saving…",
    envPlaceholder: "Enter value…",
    envEmpty: "No env keys reported by the server.",
    envConfirmTitle: "Update connection setting",
    envConfirmBody: (key: string) =>
      `Update ${key}? This overwrites the value stored on this machine.`,

    testTitle: "Test connections",
    testForma: "Test Forma",
    testRevit: "Test Revit",
    testRunning: "Testing…",
    testVersionSuffix: (version: string) => ` (v${version})`,

    diagnosticsTitle: "Diagnostics",
    diagnosticsRun: "Run diagnostics",
    diagnosticsRunning: "Running…",
    diagnosticsColumnCheck: "Check",
    diagnosticsColumnStatus: "Status",
    diagnosticsColumnDetail: "Detail",
    diagnosticsEmpty: "Run diagnostics to see results.",
    diagnosticsStatus: {
      pass: "Pass",
      warn: "Warn",
      fail: "Fail",
    },

    aboutTitle: "About",
    aboutVersion: (version: string) => `AutoAudit ${version}`,
    aboutDocsNote: "See PILOT_INSTALL.md for full setup and deployment docs.",
  },
  bucket: {
    compliant: "Compliant",
    non_compliant: "Non-compliant",
    manual_review: "Manual review",
    missing_data: "Missing data",
  },
  severity: {
    high: "High",
    medium: "Medium",
    low: "Low",
  },
  run: {
    title: "Run an audit",
    description: "Choose a profile or configure a quick run, then start the audit.",
    tabProfile: "Profile",
    tabQuickRun: "Quick run",
    profileSelect: "Profile",
    profileRulesCount: (n: number) => `${n} rule${n === 1 ? "" : "s"}`,
    rulesSelect: "Rules",
    modeSelect: "Mode",
    modeApply: "Issues only (ACC)",
    modeRunRevit: "Full run (Revit + ACC)",
    modeDemo: "Demo (mock)",
    dryRun: "Dry run",
    advanced: "Advanced",
    maxIssues: "Max ACC issues",
    maxElements: "Max elements",
    preflight: "Pre-flight",
    submit: "Start audit",
    submitting: "Starting…",
    conflictBanner: "Another audit is running",
    viewRunning: "View running audit",
    validationTitle: "Fix these before starting",
    failedEarlyTitle: "Audit failed to start",
    failedEarlyBody: "The audit failed before a run folder was created.",
  },
  liveRun: {
    title: "Live run",
    phases: {
      service: "Started",
      axes: "Audit axes",
      query: "Query",
      qc: "Quality check",
      design: "Design",
      record: "Recording",
      run: "Finished",
    },
    failed: "Audit failed",
    viewTrace: "View trace",
    reconnecting: "Reconnecting…",
  },
  runDetail: {
    iterations: (n: number) => `${n} iteration${n === 1 ? "" : "s"}`,
    rules: "Rules",
    findings: "Findings",
    exportCsv: "Export CSV",
    exportDocx: "Export DOCX",
    exportPdf: "Export PDF",
    createViews: "Create verification views",
    highlight: "Highlight in Revit",
    highlightDisabledTooltip: "Revit is not connected",
    accIssue: "ACC issue",
    columnElement: "Element",
    columnParameter: "Parameter",
    columnValue: "Value",
    columnSuggested: "Suggested",
    columnBucket: "Bucket",
    columnSeverity: "Severity",
    columnRule: "Rule",
    filterBucket: "Bucket",
    filterSeverity: "Severity",
    filterSearch: "Search element or value",
    allRules: "All rules",
    tabReport: "Report",
    tabVerificationReport: "Verification report",
    tabTrace: "Trace",
    noSelection: "Select a finding to see details",
    detailTitle: "Finding detail",
    artifactMissing: (name: string) => `This run has no ${name}.`,
    confirmExportTitle: "Export report",
    confirmExportBody: "Generate a report file in the run folder?",
    confirmViewsTitle: "Create verification views",
    confirmViewsBody:
      "This creates Revit schedules in the open document. Continue?",
    confirmHighlightTitle: "Highlight in Revit",
    // 2026-08-17: the old wording ("select and zoom") promised less than the
    // action does — it ACTIVATES a view per level (Revit's ShowElements can
    // change the active view on its own, and we now walk each level's plan
    // deliberately). Nothing is written to the model.
    confirmHighlightBody: (n: number) =>
      `Select ${n} element${n === 1 ? "" : "s"} in the live Revit model and open ` +
      `each one's level plan to frame them? This changes the active view; ` +
      `nothing is written to the model.`,
  },
  runsPage: {
    title: "History",
    description: "Every audit run, its outcome mix, and the compliance trend over time.",
    columnRunId: "Run",
    columnMode: "Mode",
    columnStarted: "Started",
    columnDuration: "Duration",
    columnStatus: "Status",
    columnCompliance: "Compliance",
    corruptTooltip: "This run folder is missing or corrupt metadata",
    emptyTitle: "No runs yet",
    emptyBody: "Start an audit to see it listed here.",
    emptyAction: "Run an audit",
  },
  trend: {
    title: "Trend",
    resolved: "Resolved",
    new: "New",
    persistent: "Persistent",
    empty: "Not enough runs yet to show a trend.",
  },
  approvals: {
    title: "Approvals",
    description: "Path-B proposals awaiting an ACC status change before they write to Revit.",
    applyNow: "Apply approved now",
    pendingCount: (n: number) => `${n} pending`,
    appliedCount: (n: number) => `${n} applied`,
    ignoredSection: "Ignored",
    ignore: "Ignore",
    restore: "Restore",
    caption: "Applies only proposals whose ACC issue is set to In progress.",
    statusPending: "Pending",
    statusApplied: "Applied",
    statusAppliedIssueOpen: "Applied — issue open",
    statusIgnored: "Ignored",
    inheritedFromHost: "host",
    resultBanner: (applied: number, held: number) =>
      `Applied ${applied}, held back ${held}`,
    heldExplanation:
      "Held = fingerprint/stale gate — the write-set changed or drifted since the proposal was created.",
    emptyTitle: "No proposals yet",
    emptyBody: "Run an audit with auto-fix rules to see proposals here.",
    confirmIgnoreTitle: "Ignore proposal",
    confirmIgnoreBody: "Move this proposal to the ignored list?",
    confirmRestoreTitle: "Restore proposal",
    confirmRestoreBody: "Move this proposal back to pending?",
    confirmApplyTitle: "Apply approved proposals",
    confirmApplyBody:
      "Apply every approved (In progress) proposal now? This writes to Revit/ACC.",
    accIssueLink: "ACC issue",
    fingerprintOk: "fingerprint ok",
  },
  extractPdf: {
    title: "Extract rules from PDF",
    description:
      "Upload a BEP / IBC / spec PDF — the extractor drafts a rule set for you to review before saving.",
    chooseFile: "Choose PDF…",
    selectedFile: (name: string) => `Selected: ${name}`,
    extract: "Extract",
    extracting: "Extracting…",
    extractingHint: "This can take up to a few minutes for long documents.",
    maxSections: "Max sections (optional)",
    maxSectionsPlaceholder: "e.g. 12 — for a quick demo",
    maxSectionsHint: "Limit to the first N sections. Leave blank to process the whole document.",
    notInstalledTitle: "Extraction not available",
    parseFailedTitle: "Could not parse this PDF",
    warningsTitle: "Warnings",
    reviewTitle: "Review extracted rules",
    reviewCount: (n: number) => `${n} rule${n === 1 ? "" : "s"} extracted`,
    columnRuleId: "ID",
    columnCategory: "Category",
    columnParameter: "Parameter",
    columnRequirement: "Requirement",
    scenario: "Scenario name",
    scenarioPlaceholder: "e.g. vp_bep",
    scenarioHint: (name: string) => `Will save to config/rules.${name || "…"}.yaml`,
    save: "Save as rules file",
    saving: "Saving…",
    savedBody: (path: string) => `Saved to ${path}`,
    overwriteTitle: "Overwrite existing file",
    overwriteBody:
      "A rules file with this scenario name already exists. Overwrite it with the extracted rules?",
    startOver: "Start over",
  },
  common: {
    cancel: "Cancel",
    confirm: "Confirm",
    close: "Close",
    loading: "Loading…",
    error: "Something went wrong",
    retry: "Retry",
    copy: "Copy",
    copied: "Copied",
    save: "Save",
  },
} as const;
